/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/y9Za8lvczuC
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.5rem;
}
**/
import Link from "next/link";
import {
	Card,
	CardHeader,
	CardTitle,
	CardDescription,
	CardContent,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import { PodcastIcon } from "../icons/podcastIcon";
import { AirplayIcon } from "../icons/airplayIcon";
import { AppleIcon } from "../icons/appleIcon";
import { GhostIcon } from "../icons/ghostIcon";
import { RecentPods } from "./recent-pods";
import { Suspense } from "react";
import { SkeletonRecentPods } from "../skeletons/skeleton-recent-pods";

export function LandingPage() {
	return (
		<>
			<section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
				<div className="container px-4 md:px-6">
					<div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
						<Image
							src="/placeholder.svg"
							width="550"
							height="550"
							alt="Hero"
							className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
						/>
						<div className="flex flex-col justify-center space-y-4">
							<div className="space-y-2">
								<h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
									Oooh, Spooky
								</h1>
								<p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
									Join us as we explore the world of the paranormal, the
									unexplained, and the downright spooky. Get ready for a
									spine-tingling adventure!
								</p>
							</div>
							<Link
								href="#"
								className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
								prefetch={false}
							>
								Listen Now
							</Link>
						</div>
					</div>
				</div>
			</section>
			<Suspense fallback={<SkeletonRecentPods />}>
				<RecentPods />
			</Suspense>
			<section id="hosts" className="w-full py-12 md:py-24 lg:py-32">
				<div className="container px-4 md:px-6">
					<div className="flex flex-col items-center justify-center space-y-4 text-center">
						<div className="space-y-2">
							<div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
								Meet the Hosts
							</div>
							<h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
								Your spooky guides
							</h2>
							<p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
								Meet the hosts of Oooh, Spooky, who will take you on a thrilling
								journey into the world of the paranormal.
							</p>
						</div>
					</div>
					<div className="mx-auto grid max-w-4xl items-center gap-6 py-12 sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
						<Card className="h-full w-full">
							<CardHeader>
								<Image
									src="/placeholder.svg"
									width="200"
									height="200"
									alt="Host 1"
									className="mx-auto aspect-square overflow-hidden rounded-full object-cover"
								/>
							</CardHeader>
							<CardContent>
								<CardTitle>Jane Doe</CardTitle>
								<CardDescription>
									Jane is a paranormal investigator and author with a passion
									for exploring the unknown.
								</CardDescription>
							</CardContent>
						</Card>
						<Card className="h-full w-full">
							<CardHeader>
								<Image
									src="/placeholder.svg"
									width="200"
									height="200"
									alt="Host 2"
									className="mx-auto aspect-square overflow-hidden rounded-full object-cover"
								/>
							</CardHeader>
							<CardContent>
								<CardTitle>John Smith</CardTitle>
								<CardDescription>
									John is a historian and expert on urban legends and folklore,
									with a knack for storytelling.
								</CardDescription>
							</CardContent>
						</Card>
						<Card className="h-full w-full">
							<CardHeader>
								<Image
									src="/placeholder.svg"
									width="200"
									height="200"
									alt="Host 3"
									className="mx-auto aspect-square overflow-hidden rounded-full object-cover"
								/>
							</CardHeader>
							<CardContent>
								<CardTitle>Sarah Johnson</CardTitle>
								<CardDescription>
									Sarah is a cryptozoologist and expert on cryptids and
									legendary creatures, with a passion for adventure.
								</CardDescription>
							</CardContent>
						</Card>
					</div>
				</div>
			</section>
			<section
				id="other-podcasts"
				className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800"
			>
				<div className="container px-4 md:px-6">
					<div className="flex flex-col items-center justify-center space-y-4 text-center">
						<div className="space-y-2">
							<div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
								Our Other Podcasts
							</div>
							<h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
								More from our network
							</h2>
							<p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
								Check out our other popular podcasts covering a wide range of
								topics and interests.
							</p>
						</div>
					</div>
					<div className="mx-auto grid max-w-4xl items-center gap-6 py-12 sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
						<Card className="h-full w-full">
							<CardHeader>
								<CardTitle>Filthy Casuals</CardTitle>
								<CardDescription>
									A podcast about gaming, pop culture, and more.
								</CardDescription>
							</CardHeader>
							<CardContent>
								<Button variant="ghost" className="w-full">
									Listen
								</Button>
							</CardContent>
						</Card>
						<Card className="h-full w-full">
							<CardHeader>
								<CardTitle>Kentucky Fried Chattin&apos;</CardTitle>
								<CardDescription>
									Join us for casual conversations about life, love, and
									everything in between.
								</CardDescription>
							</CardHeader>
							<CardContent>
								<Button variant="ghost" className="w-full">
									Listen
								</Button>
							</CardContent>
						</Card>
						<Card className="h-full w-full">
							<CardHeader>
								<CardTitle>Going Hypo</CardTitle>
								<CardDescription>
									A podcast exploring the world of health and wellness.
								</CardDescription>
							</CardHeader>
							<CardContent>
								<Button variant="ghost" className="w-full">
									Listen
								</Button>
							</CardContent>
						</Card>
					</div>
				</div>
			</section>
			<section id="subscribe" className="w-full py-12 md:py-24 lg:py-32 ">
				<div className="container px-4 md:px-6">
					<div className="flex flex-col items-center justify-center space-y-4 text-center">
						<div className="space-y-2">
							<div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
								Subscribe
							</div>
							<h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
								Don&apos;t miss an episode
							</h2>
							<p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
								Subscribe to our podcast on your favorite platform and never
								miss an episode of Oooh, Spooky.
							</p>
						</div>
					</div>
					<div className="mx-auto grid max-w-4xl items-center gap-6 py-12 sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
						<Link
							href="#"
							className="flex h-16 w-full items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
							prefetch={false}
						>
							<AppleIcon className="h-6 w-6 mr-2" />
							Apple Podcasts
						</Link>
						<Link
							href="#"
							className="flex h-16 w-full items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
							prefetch={false}
						>
							<AirplayIcon className="h-6 w-6 mr-2" />
							Spotify
						</Link>
						<Link
							href="#"
							className="flex h-16 w-full items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
							prefetch={false}
						>
							<PodcastIcon className="h-6 w-6 mr-2" />
							Google Podcasts
						</Link>
					</div>
				</div>
			</section>
			<section
				id="patreon"
				className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800"
			>
				<div className="container px-4 md:px-6">
					<div className="flex flex-col items-center justify-center space-y-4 text-center">
						<div className="space-y-2">
							<div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
								Patreon
							</div>
							<h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
								Exclusive Content
							</h2>
							<p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
								Support us on Patreon and get access to exclusive podcasts every
								week, behind-the-scenes content, and more!
							</p>
						</div>
					</div>
					<div className="mx-auto grid max-w-4xl items-center gap-6 py-12 sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-1">
						<Link
							href="#"
							className="flex h-16 w-full items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
							prefetch={false}
						>
							<GhostIcon className="h-6 w-6 mr-2" />
							Join Patreon
						</Link>
					</div>
				</div>
			</section>
		</>
	);
}
